version: "3.9"
services:
  python:
    build:
      context: .
      dockerfile: .docker/python/Dockerfile
    restart: always
    ports:
      - 80:80
    links: 
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ULS4RC14Td2J
      POSTGRES_DB: main
    ports:
      - 5432:5432
    volumes: 
      - ./database:/var/lib/postgresql/data
      - ./.docker/postgres:/docker-entrypoint-initdb.d

  cron:
    build:
      context: .
      dockerfile: .docker/cron/Dockerfile
    restart: always
    links:
      - python
