version: "3.9"
services:
  python:
    build:
      context: .
      dockerfile: .docker/python/Dockerfile
    restart: always
    ports:
      - 80:80
    links: 
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    