"""init

Revision ID: 226d60933df1
Revises: 
Create Date: 2021-08-12 21:29:28.920899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '226d60933df1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prozorro_sale_auctions_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_id', sa.String(length=255), nullable=True),
    sa.Column('auction_id', sa.String(length=255), nullable=True),
    sa.Column('date_published', sa.TIMESTAMP(), nullable=True),
    sa.Column('date_modified', sa.TIMESTAMP(), nullable=True),
    sa.Column('object', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='src'
    )
    op.create_index('prozorro_sale_auctions_history_id_date_modified_idx', 'prozorro_sale_auctions_history', ['_id', sa.text('date_modified DESC')], unique=False, schema='src')
    op.create_table('prozorro_sale_objects_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_id', sa.String(length=255), nullable=True),
    sa.Column('registry_object_id', sa.String(length=255), nullable=True),
    sa.Column('date_published', sa.TIMESTAMP(), nullable=True),
    sa.Column('date_modified', sa.TIMESTAMP(), nullable=True),
    sa.Column('object', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='src'
    )
    op.create_index('prozorro_sale_objects_history_id_date_modified_idx', 'prozorro_sale_objects_history', ['_id', sa.text('date_modified DESC')], unique=False, schema='src')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('prozorro_sale_objects_history_id_date_modified_idx', table_name='prozorro_sale_objects_history', schema='src')
    op.drop_table('prozorro_sale_objects_history', schema='src')
    op.drop_index('prozorro_sale_auctions_history_id_date_modified_idx', table_name='prozorro_sale_auctions_history', schema='src')
    op.drop_table('prozorro_sale_auctions_history', schema='src')
    # ### end Alembic commands ###
